### root page
GET http://localhost:3000/

### greet
POST https://nodeexamples-dot-pt-srh-dev.ey.r.appspot.com/greet
Content-Type: application/json

{
    "name": "Bob"
}


### List All Persons
GET http://localhost:3000/persons

### Get Person by ID
GET http://localhost:3000/persons/1

### Create New Person
POST http://localhost:3000/persons
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Smith"
}

### Create New Person
POST http://localhost:3000/persons
Content-Type: application/json

{
    "firstName": "Alice",
    "lastName": "Cooper"
}

### Create New Person
POST http://localhost:3000/persons
Content-Type: application/json

{
    "firstName": "Frank",
    "lastName": "Zappa",
    "age": 65
}

### Update Person
PUT http://localhost:3000/persons/1
Content-Type: application/json

{
    "firstName": "Bob Updated",
}

### Delete Person
DELETE http://localhost:3000/persons/1
